### ISSUE TITLE
Everything worked perfect in local environment, but not when uploaded

### ISSUE THREAD

**Issue by danhodkinson** [olada/MyBBIntegrator#12]
I have integrated wordpress to run 'alongside' mybb, had to change a few functions but had it all working perfectly. I only use Wordpress to handle a CMS section of the site so MyBBIntegrator is still being used for what it should be used for.

I had this working perfectly locally. It would login, logout, redirect if user wasn't logged in.

I have since uploaded to my server on a subdomain and cannot get this thing to work for logging in and out, the other calls for recent topics, active threads all work but not log in/out.

I am running:
`global $mybb, $lang, $query, $db, $cache, $plugins, $displaygroupfields;
require_once './forum/global.php';
require_once 'class.MyBBIntegrator.php';
$MyBBI = new MyBBIntegrator($mybb, $db, $cache, $plugins, $lang, $config);`

then my first test to see if the user is logged in is:
`<?php if ($MyBBI->isLoggedIn() == false){
    header('Location: login');
}?>`

but it does nothing, whereas locally it does.

I'm thinking maybe it's a cookie path issue, i've updated my MyBB cookie settings and URL. But really not sure?

Any help is much appreciated

**Comment by danhodkinson** [comment]
i've been digging deeper. If i login on my login page it logs in, but then as soon as i navigate to another page it forgets that i'm logged in. It seems as though the 'mybbuser' cookie isn't being set when logging in?

**Comment by olada** [comment]
This surely sounds like a cookie issue, since it worked in your local environment..
Where is the website located and where is the forum located relative to each other?

**Comment by olada** [comment]
Closed because of inactivity.
