### ISSUE TITLE
Is this plugin still being worked on? if so, login issue.

### ISSUE THREAD

**Issue by danhodkinson** [olada/MyBBIntegrator#7]
I have a strange login issue.

- If i login with the correct details then it works fine.
- If i fail the login x amount of times so it hits mybb's `logincount` limit then when i clear that cookie I can no longer login?
- the only way I can then login is to login through the mybb forum.

any ideas why this would be?

**Comment by olada** [comment]
Hi, 

yes, the library is still being worked on. I am currently working on a new release to be up-to-date with the 1.8 releases of MyBB.
What version of MyBB are you using?

**Comment by danhodkinson** [comment]
I have never received such a quick reply on a git issue!

I'm on 1.8.6, happy to go through the code i'm using with you (it involves unsetting the mybb cookies and things). 

Do you have an estimate on the release date at all?

**Comment by olada** [comment]
Thanks for the warm words, I'm trying to improve on maintaining my public
projects.

I was planning on increasing the code coverage up to 70%, but can of course
commit the current state and increment the coverage as we go.
Part of the process is to bring the integrator up to date for the 1.8
releases, so the next commit might already be the fix you are looking for.
As you can imagine, this commit won't be a tagged release.

I will try to take care of it later this evening - in a few hours.
Am 04.05.2016 3:08 nachm. schrieb "Dan Hodkinson" <notifications@github.com

**Comment by danhodkinson** [comment]
Sounds perfect. Just let me know the release (when it's ready) and i'll happily test it with the issue i've been having. Everything else works fine, or i've managed to work around.

**Comment by olada** [comment]
Unfortunately took a little longer than promised, but I have just committed the most recent version which is being worked on.
Feel free to check.

**Comment by aa6my** [comment]
Good Job @olada

**Comment by danhodkinson** [comment]
forgot to say, this worked perfectly!

**Comment by danhodkinson** [comment]
looking forward to seeing what else is going to be added in the new version

**Comment by olada** [comment]
Nice to hear that the revamp is tackling your issue. 
Closing this one.
